# Generated by Django 3.0.8 on 2020-08-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('materials', models.ManyToManyField(related_name='lessons', to='lesson.Material')),
            ],
        ),
    ]
